In [3]:
import FuncionesMEF3D as M3D
import numpy as np

nu = 0.3
E = 0
elemento = 0
MN = np.array([[1, 1, 2],
               [0, 0, 0],
               [0, 2, 0],
               [2, 1, 0]])

MC = np.array([[0, 1, 2, 3]])

Kel,D,B = M3D.k_elemental_3D(MN, MC, nu, E, elemento)
print(B)


D
[[0.7 0.3 0.3 0.  0.  0. ]
 [0.3 0.7 0.3 0.  0.  0. ]
 [0.3 0.3 0.7 0.  0.  0. ]
 [0.  0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.  0.2]]
B1
[[-0.   0.   0. ]
 [ 0.   0.   0. ]
 [ 0.   0.   0.5]
 [ 0.  -0.   0. ]
 [ 0.   0.5  0. ]
 [ 0.5  0.  -0. ]]
B2
[[-0.25   0.     0.   ]
 [ 0.    -0.5    0.   ]
 [ 0.     0.    -0.125]
 [-0.5   -0.25   0.   ]
 [ 0.    -0.125 -0.5  ]
 [-0.125  0.    -0.25 ]]
B3
[[-0.25   0.     0.   ]
 [ 0.     0.5    0.   ]
 [ 0.     0.    -0.125]
 [ 0.5   -0.25   0.   ]
 [ 0.    -0.125  0.5  ]
 [-0.125  0.    -0.25 ]]
B4
[[ 0.5   0.    0.  ]
 [ 0.   -0.    0.  ]
 [ 0.    0.   -0.25]
 [-0.    0.5   0.  ]
 [ 0.   -0.25 -0.  ]
 [-0.25  0.    0.5 ]]
[[-0.     0.     0.    -0.25   0.     0.    -0.25   0.     0.     0.5
   0.     0.   ]
 [ 0.     0.     0.     0.    -0.5    0.     0.     0.5    0.     0.
  -0.     0.   ]
 [ 0.     0.     0.5    0.     0.    -0.125  0.     0.    -0.125  0.
   0.    -0.25 ]
 [ 0.    -0.     0.    -0.5   -0.25   