$$\LARGE
\underline
{
\textbf
    {Problema 2}
}
$$

Considere el entramado mostrado en la figura, con una fuerza aplicada de 20 kN. Calcule los
desplazamientos de cada uno de los nodos y las tensiones que sufre cada elemento. Todos los
elementos tienen $E = 210\ GPa$ y una sección de $10 cm^{2}$, excepto el elemento 3, que tiene una
sección de $20 cm^{2}$. Los elementos 2 y 5 tienen una longitud de 8 metros y el elemento 3 de 4
metros.

<center><img src="ImgProb02G02.png"></center>

In [1]:
import numpy as np
import MEF as mef

In [2]:
glxn = 2  # grados de libertad por nodo

<div style="background:#999900"> Las fuerzas del resultado parecen estar bien, deberías tener dos fuerzas en y iguales (en las puntas del puente) compensando la carga. Fijate en el ejemplo del repositorio que esta el resultado !</div>

In [3]:
MN = np.array([[0,0,0],[8,0,0],[16,0,0],[8,4,0]])  # pos de cada nodo  # metros
MC = np.array([[0,3],[0,1],[1,3],[2,3],[1,2]])  # ensamble entre elementos
E = np.array([210,210,210,210,210])*1e9  # GPa
A = np.array([10,10,20,10,10])/(100**2)  # m2

s = np.array([0,1,5])
r = mef.vector_complemento(s, MN, glxn)

Fr = np.array([0,0,-20,0,0]).reshape([-1,1])*1e3
Us = np.array([0, 0, 0]).reshape([-1,1])

<div style="background:#999900">Me parece que el problema es que esta mal la fuerza de input</div>

In [4]:
MN

array([[ 0,  0,  0],
       [ 8,  0,  0],
       [16,  0,  0],
       [ 8,  4,  0]])

In [5]:
Fr = np.array([[0],[-20e3],[0],[0],[8]])

In [6]:
K, Ke = mef.Kglobal_barra(MN, MC, E, A, glxn)

In [7]:
F, U = mef.solve1D(K, r, s, Us, Fr)

In [8]:
np.set_printoptions(formatter={"float": lambda x: "%0.3f"% (x)})
print('\033[4m'+f'\nVector fuerzas' +'\033[0m'+'[KN]:\n\033[93m'+f'F = \n{F/1000}\n'+'\033[0m')
print('\033[4m'+f'Vector desplazamientos'+'\033[0m'+'[mm]:\n\033[93m'+ f'U =\n {U*1000} \n')


Vector fuerzas[KN]:
F = 
[[0.000]
 [9.996]
 [0.000]
 [-20.000]
 [0.000]
 [9.996]
 [0.000]
 [0.008]]

Vector desplazamientos[mm]:
U =
 [[0.000]
 [0.000]
 [0.762]
 [-3.842]
 [1.523]
 [0.000]
 [0.762]
 [-3.652]] 

